module "lambda-cloudwatch-notify-slack" {
  source                                    = "../modules/lambda-cloudwatch-notify-slack"

  AWS_REGION                                = "${var.AWS_REGION}"
  DBG_NAMING_PREFIX                         = "${var.DBG_NAMING_PREFIX}"
  AWS_PROVIDER_ASSUME_ROLE                  = "${var.AWS_PROVIDER_ASSUME_ROLE}"
  TAG_PRODUCT                               = "${var.TAG_PRODUCT}"
  TAG_COSTCENTER                            = "${var.TAG_COSTCENTER}"
  TAG_APPLICATIONID                         = "${var.TAG_APPLICATIONID}"
  TAG_APPLICATION                           = "${var.TAG_APPLICATION}"
  TAG_PROJECT                               = "${var.TAG_PROJECT}"
  TAG_CRITICALITY                           = "${var.TAG_CRITICALITY}"
  TAG_SUPPORT_EMAIL                         = "${var.TAG_SUPPORT_EMAIL}"
  TAG_SUPPORT_SLACK                         = "${var.TAG_SUPPORT_SLACK}"
  TAG_ENVIRONMENT                           = "${var.TAG_ENVIRONMENT}"
  ENVIRONMENT                               = "${var.ENVIRONMENT}"
  DEPLOY_NAME                               = "${var.DEPLOY_NAME}"
  PRODUCT_NAME                              = "${var.PRODUCT_NAME}"
  OWNER                                     = "${var.OWNER}"
  SNS_TOPIC_NAME                            = "${var.SNS_TOPIC_NAME}"
  SLACK_WEBHOOK_URL                         = "${var.SLACK_WEBHOOK_URL}"
  SLACK_CHANNEL                             = "${var.SLACK_CHANNEL}"
  SLACK_USERNAME                            = "${var.SLACK_USERNAME}"
  LAMBDA_FUNCTION_NAME                      = "${var.LAMBDA_FUNCTION_NAME}"
}


module "lambda-cloudwatch-alarms" {
  source                                    = "../modules/lambda-cloudwatch-alarms"

  AWS_REGION                                = "${var.AWS_REGION}"
  DBG_NAMING_PREFIX                         = "${var.DBG_NAMING_PREFIX}"
  AWS_PROVIDER_ASSUME_ROLE                  = "${var.AWS_PROVIDER_ASSUME_ROLE}"
  ELASTIC_SUBDOMAIN                         = "${var.ELASTIC_SUBDOMAIN}"
  DOMAIN                                    = "${var.DOMAIN}"
  SUBDOMAIN                                 = "${var.SUBDOMAIN}"
  TAG_PRODUCT                               = "${var.TAG_PRODUCT}"
  TAG_COSTCENTER                            = "${var.TAG_COSTCENTER}"
  TAG_APPLICATIONID                         = "${var.TAG_APPLICATIONID}"
  TAG_APPLICATION                           = "${var.TAG_APPLICATION}"
  TAG_PROJECT                               = "${var.TAG_PROJECT}"
  TAG_CRITICALITY                           = "${var.TAG_CRITICALITY}"
  TAG_SUPPORT_EMAIL                         = "${var.TAG_SUPPORT_EMAIL}"
  TAG_SUPPORT_SLACK                         = "${var.TAG_SUPPORT_SLACK}"
  TAG_ENVIRONMENT                           = "${var.TAG_ENVIRONMENT}"
  ENVIRONMENT                               = "${var.ENVIRONMENT}"
  DEPLOY_NAME                               = "${var.DEPLOY_NAME}"
  PRODUCT_NAME                              = "${var.PRODUCT_NAME}"
  OWNER                                     = "${var.OWNER}"
  ACCOUNT_ID                                = "${var.ACCOUNT_ID}"
  SSM_USERNAME_KEY                          = "${var.SSM_USERNAME_KEY}"
  SSM_PASSWORD_KEY                          = "${var.SSM_PASSWORD_KEY}"
  SUBNETS                                   = "${var.SUBNETS}"
  VPC_ID                                    = "${var.VPC_ID}"
  KMS_KEY_ID                                = "${var.KMS_KEY_ID}"
  SLACK_TOPIC_ARN                           = "${module.lambda-cloudwatch-notify-slack.SLACK_TOPIC_ARN}"
  NOTIFY_SLACK_LAMBDA_FUNCTION_NAME         = "${module.lambda-cloudwatch-notify-slack.NOTIFY_SLACK_LAMBDA_FUNCTION_NAME}"
  CLOUDWATCH_NAMESPACE                      = "${var.CLOUDWATCH_NAMESPACE}"
}

